"""
seed_data.py — single source of truth for the ONE-TENANT demo dataset
=====================================================================
`build()` returns one fully-resolved tenant dataset (WZB Group) with deterministic
IDs, so the reseed is idempotent. Both the DB reseeder (`seed_demo.py`) and the
upload-file generator (`seed_files.py`) consume this module, and `eval_recon.py`
scores a real reconcile run against the ground-truth expectations map emitted here.

The tenant has:
  • 2 bank accounts, both MYR: A1 Maybank (primary, manual/upload statements) and
    A2 CIMB (Finverse bank-feed linked → `source="bankfeed"` transactions). A third
    account is added LIVE on stage via the Finverse testbank connect.
  • A completed HISTORICAL reconciliation job (auto + human-`manual` matches) giving
    learned-memory exemplars + a per-counterparty amount baseline for the outlier check.
  • A pre-seeded CURRENT set (~75 pending invoices across MyInvois/AutoCount/SQL/upload
    sources + ~100 transactions + ~75 proofs) — the live reconcile/verify/anomaly demo.
  • A FILE set (~quarter of the documents) delivered only under test_files/; uploading
    them exercises the real parse pipeline without duplicating anything in the DB.

Every pending invoice is assigned a DIFFICULTY TIER and a ground-truth outcome, so the
matcher's real accuracy is measurable (and deliberately < 100%):
  A  reference match  → deterministic pre-pass auto-commit
  B  clean semantic   → LLM should auto-match (unique party, exact amount, has proof)
  C  mild ambiguity   → FX rounding / small fee variance / generic description
  D  hard             → near-duplicate amounts, split payment, competing candidates,
                        stale date, abbreviated party — the accuracy-limiters
  E  should-not-auto  → unmatched / overpaid-escalate / high-value-no-proof / weak link
                        / beneficiary mismatch / bank-detail change / amount outlier /
                        duplicate invoice
Plus non-scored FAILURE paths: failed invoice parse, failed proof parse (and invalid
upload files generated by seed_files.py).
"""
import hashlib
import os
import random
import uuid
from datetime import date, datetime, timezone

# Volume knob for stress-testing recon time. The LLM-matcher path (Tiers B/C/D, no
# reference) is what drives recon wall-clock — the reference pre-pass + rules are cheap.
# Default 38 = the tight ~7-min demo; set SEED_LLM_TARGET=100 for an offline stress run.
LLM_TARGET = int(os.getenv("SEED_LLM_TARGET", "38"))

# Stable namespace → every id is uuid5(NS, business-key): re-running yields the
# exact same UUIDs so inserts upsert in place.
NS = uuid.UUID("5eed5eed-0000-4000-8000-0000000dec0d")

DEMO_PASSWORD = "TreasuryFlow#2026"

# Time-saved model (tunable knobs, read by eval_recon.py).
# ponytail: flat per-doc constants, not a measured human time-study — swap in a real
# baseline if one exists.
TIME_MODEL = {"manual_min_per_invoice": 8.0, "review_min_per_flag": 3.0}


def uid(*parts) -> str:
    return str(uuid.uuid5(NS, "|".join(str(p) for p in parts)))


def _utc_iso(d: date) -> str:
    return datetime.combine(d, datetime.min.time()).replace(tzinfo=timezone.utc).isoformat()


def txid(account_id: str, date_iso: str, description: str, signed_amount: float,
         occurrence: int = 0) -> str:
    """Replicate statement_parser's account-scoped transaction id so a seeded
    transaction is identical to one produced by uploading the same statement."""
    base = hashlib.sha256(
        f"{date_iso}|{description.upper()}|{round(signed_amount, 2)}|{occurrence}".encode()
    ).hexdigest()
    return hashlib.sha256(f"{account_id}|{base}".encode()).hexdigest()


# ── FX (per-unit). rate is "1 FROM = <rate> TO". Upserted, keyed to the invoice date. ──
RATES = {
    ("USD", "MYR"): 4.72, ("EUR", "MYR"): 5.10, ("SGD", "MYR"): 3.49,
}


def rate_for(frm: str, to: str) -> float:
    if frm == to:
        return 1.0
    return RATES[(frm, to)]


# ── The one tenant ─────────────────────────────────────────────────
# WZB keeps its long-documented sme_id + Maybank account id + demo email so the
# existing handoff docs/logins stay valid.
SME_DEFS = [
    {
        "sme_id": "111e4567-e89b-12d3-a456-426614174111",
        "slug": "wzb_group", "company_name": "WZB Group Sdn Bhd",
        "registration_no": "202301012345", "email": "finance@wzbgroup.my",
        "phone": "+60312345678", "country_code": "MY", "base_ccy": "MYR",
        # (fixed_id, bank, acct_no, ccy, primary, stmt_source)
        "accounts": [
            ("999e4567-e89b-12d3-a456-426614174999", "Maybank", "512345678901", "MYR", True, "upload"),
            (None, "CIMB Bank", "700112233445", "MYR", False, "bankfeed"),
        ],
    },
]


def _accounts(sme):
    out = []
    for i, (fixed_id, bank, acct_no, ccy, primary, _src) in enumerate(sme["accounts"]):
        out.append({
            "account_id": fixed_id or uid("acct", sme["sme_id"], i),
            "sme_id": sme["sme_id"], "account_holder": sme["company_name"],
            "account_number": acct_no, "bank_name": bank, "currency_code": ccy,
            "is_active": True, "is_primary": primary,
        })
    return out


# Unique counterparty pool for the clean "filler" invoices (unambiguous → reliably matched).
_CP_POOL = [
    "Globex Ltd", "Initech Sdn Bhd", "Umbrella Trading", "Soylent Corp",
    "Hooli Malaysia", "Pied Piper Sdn Bhd", "Vehement Capital", "Massive Dynamic",
    "Stark Industries Asia", "Wayne Enterprises SEA", "Wonka Foods Sdn Bhd",
    "Gekko Holdings", "Tyrell Trading", "Oceanic Freight", "Nakatomi Trading",
    "Vandelay Industries", "Prestige Worldwide", "Monarch Sdn Bhd",
    "Bright Star Logistics", "Golden Harvest Foods", "Silver Peak Trading",
    "Evergreen Textiles", "Summit Components", "Pacific Rim Exports",
    "Highland Timber Sdn Bhd", "Crystal Bay Seafood", "Emerald Packaging",
    "Sapphire Electronics", "Ruby Chemicals Sdn Bhd", "Topaz Machinery",
    "Onyx Steel Trading", "Jade Garden Produce", "Coral Reef Imports",
    "Amber Fields Agro", "Cobalt Manufacturing", "Indigo Apparel",
    "Scarlet Dyes Sdn Bhd", "Violet Ventures", "Meridian Logistics Bhd",
    "Zenith Trading Co", "Apex Distributors", "Nusantara Agro Bhd",
    "Straits Timber Trading", "Peninsula Chemicals", "Borneo Palm Exports",
    "Klang River Logistics", "Georgetown Spice Co", "Malacca Bay Trading",
    "Kinabalu Highland Foods", "Langkawi Marine Supplies", "Putrajaya Print Works",
    "Cyberjaya Systems Sdn Bhd", "Ipoh Tin Works", "Kuching Rattan Exports",
    "Johor Steel Mills", "Perlis Rice Traders", "Terengganu Batik House",
    "Kelantan Craft Bhd", "Sarawak Timber Berhad", "Sabah Cocoa Trading",
    "Kedah Paddy Board", "Negeri Sembilan Dairy", "Pahang Gold Mining",
    "Selayang Fresh Produce", "Cheras Auto Parts", "Ampang Electronics Bhd",
    "Bangsar Textiles", "Damansara Media Group", "Subang Aerospace Supplies",
    "Shah Alam Plastics", "Petaling Steelworks", "Gombak Hardware Trading",
]

_NOISE_DESCS = [
    "DUITNOW QR PAYMENT", "FPX ONLINE TRANSFER", "MONTHLY SERVICE CHARGE",
    "SALARY PAYROLL RUN", "SST TAX REMITTANCE", "UTILITIES TNB",
    "OFFICE RENT TENANCY", "INTEREST CREDIT", "CARD SETTLEMENT",
    "INSURANCE PREMIUM", "COURIER CHARGES", "CLOUD SUBSCRIPTION",
    "ATM CASH DEPOSIT", "CHEQUE CLEARING", "STANDING INSTRUCTION",
]


def _noise_txn(account_id, ccy, rng, d):
    desc = rng.choice(_NOISE_DESCS)
    credit = desc in ("FPX ONLINE TRANSFER", "INTEREST CREDIT", "DUITNOW QR PAYMENT",
                      "ATM CASH DEPOSIT")
    amt = round(rng.uniform(40, 4200), 2)
    if desc == "INTEREST CREDIT":
        amt = round(rng.uniform(5, 90), 2)
    signed = amt if credit else -amt
    return {
        "transaction_id": txid(account_id, d, desc, signed),
        "transaction_date": d, "description": desc,
        "description_normalised": desc.upper(),
        "credit_amount": amt if credit else None,
        "debit_amount": amt if not credit else None,
        "currency_code": ccy, "is_matched": False,
    }


def _match_txn(account_id, ccy, d, desc, credit_amt, reference=None):
    return {
        "transaction_id": txid(account_id, d, desc, credit_amt),
        "transaction_date": d, "description": desc,
        "description_normalised": desc.upper(),
        "reference_number": reference,
        "credit_amount": credit_amt, "debit_amount": None,
        "currency_code": ccy, "is_matched": False,
    }


def _inv(sme_id, num, cp, ccy, amt, idate, due, *, status="pending", error=None,
         tag=None, source="upload", source_ref=None, myinvois_uuid=None, direction=None):
    return {
        "invoice_id": uid("inv", sme_id, num), "sme_id": sme_id, "invoice_number": num,
        "counterparty_name": cp, "invoice_currency": ccy, "invoice_amount": amt,
        "invoice_date": idate, "due_date": due, "status": status,
        "error_message": error, "source": source, "source_ref": source_ref,
        "myinvois_uuid": myinvois_uuid, "direction": direction, "_tag": tag,
    }


def _proof(sme_id, invoice_id, amt, ccy, pdate, ref, *, sender=None, bank=None,
           account_number=None, swift=None, status="completed", error=None, tag=None,
           uploaded=None, rail=None, recipient_reference=None):
    parsed = None
    if status == "completed":
        parsed = {"sender_name": sender, "receiver_name": None, "bank_name": bank,
                  "swift_code": swift, "iban": None, "account_number": account_number,
                  "rail": rail, "recipient_reference": recipient_reference, "raw_text": None}
        parsed = {k: v for k, v in parsed.items() if v is not None}
    return {
        "proof_id": uid("proof", sme_id, ref), "sme_id": sme_id, "invoice_id": invoice_id,
        "file_type": "pdf", "file_path": f"seed://proof-{ref}",
        "parse_status": status, "parsed_amount": amt if status == "completed" else None,
        "parsed_currency": ccy if status == "completed" else None,
        "parsed_date": pdate if status == "completed" else None,
        "parsed_reference": ref if status == "completed" else None,
        "parsed_data": parsed, "error_message": error,
        "uploaded_at": _utc_iso(date.fromisoformat(uploaded or pdate or "2026-06-01")),
        "_tag": tag,
    }


# Recurring counterparty (tight history band) → the amount-outlier baseline.
_RECURRING = "Acme Corp"
_RECURRING_BAND = 10000


def _build_history(sme, primary, rng):
    """A completed reconciliation job: matched invoices/transactions + match rows.
    Seeds learned-memory `manual` exemplars + the per-counterparty amount baseline."""
    sme_id = sme["sme_id"]
    base = sme["base_ccy"]
    job_id = uid("histjob", sme_id)
    stmt_id = uid("histstmt", sme_id)
    hist_acct = primary["account_id"]

    invoices, transactions, matches = [], [], []
    specs = []
    for i in range(4):                                   # tight cluster for the outlier baseline
        specs.append((_RECURRING, base, float(_RECURRING_BAND + i * 60), "manual" if i < 2 else "auto"))
    specs.append(("Bremen GmbH", base, _RECURRING_BAND * 1.4, "auto"))

    for i, (cp, ccy, amt, mstatus) in enumerate(specs):
        d = f"2026-05-{10 + i:02d}"
        num = f"HWZB-{i + 1:03d}"
        inv = _inv(sme_id, num, cp, ccy, amt, d, f"2026-06-{10 + i:02d}", status="matched")
        desc = f"INWARD {cp.upper()} SETTLEMENT"
        txn = _match_txn(hist_acct, base, f"2026-05-{12 + i:02d}", desc, round(amt, 2))
        txn["is_matched"] = True
        invoices.append(inv)
        transactions.append(txn)
        matches.append({
            "match_id": uid("histmatch", sme_id, num), "job_id": job_id,
            "invoice_id": inv["invoice_id"], "transaction_id": txn["transaction_id"],
            "proof_id": None, "rate_id": None, "match_confidence": 0.9,
            "invoice_amount": amt, "invoice_currency": ccy,
            "transaction_amount": round(amt, 2), "tx_currency": base,
            "converted_amount": round(amt, 2), "variance_amount": 0.0, "variance_pct": 0.0,
            "match_status": mstatus, "matched_at": _utc_iso(date.fromisoformat(d)),
        })

    statement = {"statement_id": stmt_id, "account_id": hist_acct, "file_type": "csv",
                 "file_path": "seed://history", "source": "upload",
                 "period_start": "2026-05-01", "period_end": "2026-05-31",
                 "parse_status": "completed"}
    job = {"job_id": job_id, "sme_id": sme_id, "status": "completed",
           "model_version": "seed-history", "matched_count": len(matches),
           "unmatched_count": 0, "started_at": _utc_iso(date(2026, 5, 31)),
           "completed_at": _utc_iso(date(2026, 5, 31))}
    return {"job": job, "statement": statement, "invoices": invoices,
            "transactions": transactions, "matches": matches}


def build():
    """Return the resolved tenant dataset + global FX + the ground-truth expectations."""
    datasets = []
    fx_rows = {}

    def add_fx(frm, to, d):
        if frm == to:
            return
        fx_rows[(frm, to, d)] = {
            "from_currency": frm, "to_currency": to, "rate": rate_for(frm, to),
            "effective_at": _utc_iso(date.fromisoformat(d)), "api_source": "seed"}

    for sme in SME_DEFS:
        sme_id = sme["sme_id"]
        base = sme["base_ccy"]
        rng = random.Random(uid("rng", sme_id))
        accounts = _accounts(sme)
        a1, a2 = accounts[0], accounts[1]
        history = _build_history(sme, a1, rng)

        invoices, proofs = [], []
        txns_by_acct = {a1["account_id"]: [], a2["account_id"]: []}
        expectations = []

        def _due(idate):
            return f"2026-07-{idate[-2:]}"

        def emit(num, cp, ccy, amt, idate, *, tier, expected_status, should_match,
                 source="upload", source_ref=None, myinvois_uuid=None, direction=None,
                 credits=None, proof=None, tag=None, note="", scored=True):
            """Materialise one invoice (+ optional matching credit(s) + proof) and record
            its ground-truth expectation. `credits` is a list of dicts:
            {account, day, desc, amount, ref?} — first entry's txn is the expected match."""
            inv = _inv(sme_id, num, cp, ccy, amt, idate, _due(idate), tag=tag,
                       source=source, source_ref=source_ref, myinvois_uuid=myinvois_uuid,
                       direction=direction)
            invoices.append(inv)
            if ccy != base:
                add_fx(ccy, base, idate)
            expected_txn_id = None
            for j, c in enumerate(credits or []):
                acct = c["account"]
                t = _match_txn(acct["account_id"], base, c["day"], c["desc"],
                               round(c["amount"], 2), reference=c.get("ref"))
                txns_by_acct[acct["account_id"]].append(t)
                if j == 0:
                    expected_txn_id = t["transaction_id"]
            if proof:
                proofs.append(proof(inv))
            if scored:
                # Which engine decides this row: A = deterministic reference pre-pass;
                # E = pre-pass match + deterministic gate/verifier/anomaly rules; B/C/D =
                # the LLM semantic matcher (the real "AI accuracy" number lives here).
                matcher = {"A": "reference", "E": "rules"}.get(tier, "llm")
                expectations.append({
                    "invoice_id": inv["invoice_id"], "invoice_number": num, "tier": tier,
                    "matcher": matcher, "source": source, "counterparty": cp,
                    "amount": amt, "currency": ccy,
                    "expected_transaction_id": expected_txn_id,
                    "should_match": should_match, "expected_status": expected_status,
                    "note": note,
                })
            return inv

        def credit(account, idate, desc, amount, offset=2, ref=None, day=None):
            d = day or f"2026-06-{min(28, int(idate[-2:]) + offset):02d}"
            return {"account": account, "day": d, "desc": desc,
                    "amount": amount, "ref": ref}

        def conv(ccy, amt, variance_pct=0.0):
            return round(amt * rate_for(ccy, base) * (1 + variance_pct / 100), 2)

        # Round-robin the pre-seeded invoice sources so the /uploads badges all light up.
        # A single monotonic counter guarantees unique source_ref / myinvois_uuid across
        # ALL tiers (the invoice_sme_source_ref / invoice_sme_myinvois_uuid unique indexes).
        src_cycle = ["myinvois", "autocount", "upload", "sql", "myinvois", "autocount", "upload"]
        src_ctr = [0]

        def assign_source():
            i = src_ctr[0]; src_ctr[0] += 1
            s = src_cycle[i % len(src_cycle)]
            if s == "myinvois":
                return {"source": "myinvois", "myinvois_uuid": f"seed-einv-{i:04d}", "direction": "Sent"}
            if s in ("autocount", "sql"):
                pre = "SAC" if s == "autocount" else "SQL"
                return {"source": s, "source_ref": f"{pre}-9{i:03d}", "direction": "Sent"}
            return {"source": "upload"}

        # ── Tier A — clean reference match (deterministic pre-pass auto-commit) ──
        # The txn carries the invoice number as its reference → _reference_prematch grabs
        # it. This is ~a quarter — the realistic slice of payments that arrive with the
        # invoice ref (DuitNow/FPX/e-Invoice), cleared instantly by exact-key matching.
        # The MAJORITY (Tiers B/C/D, no reference) goes through the batched LLM matcher —
        # that's the mass-reconciliation the agent must actually handle, and what eval
        # measures as the "AI accuracy". Tier E carries refs so the deterministic
        # gate/verifier/anomaly RULES (not the LLM) decide its edge-case dispositions.
        pool = list(_CP_POOL)
        rng.shuffle(pool)
        pi = 0

        def nextcp():
            nonlocal pi
            name = pool[pi % len(pool)]
            if pi >= len(pool):        # wrap: keep names unique (still unambiguous)
                name = f"{name} ({pi // len(pool) + 1})"
            pi += 1
            return name

        n_A = 18
        for k in range(n_A):
            cp = nextcp()
            num = f"WZB-A{k + 1:02d}"
            ccy = ("USD" if k % 5 == 0 else "EUR" if k % 7 == 0 else base)
            amt = round(3000 + k * 137.5, 2)
            idate = f"2026-06-{(k % 20) + 2:02d}"
            acct = a1 if k % 3 else a2
            emit(num, cp, ccy, amt, idate, tier="A", expected_status="auto", should_match=True,
                 **assign_source(),
                 credits=[credit(acct, idate, f"DUITNOW CR {cp.upper()} REF {num}",
                                 conv(ccy, amt, -0.2), ref=num)],
                 proof=(lambda inv, cp=cp, amt=amt, ccy=ccy, num=num, idate=idate:
                        _proof(sme_id, inv["invoice_id"], amt, ccy, idate, num,
                               sender=cp, bank="CIMB", rail="DuitNow", recipient_reference=num)),
                 note="reference key on the bank credit → pre-pass auto")

        # LLM-path sizing (Tiers B/C/D). D is a fixed set of 6 hand-built hard cases; C
        # (generic-description → review) scales ~15%; B (clean) fills the rest to the target.
        n_D_fixed = 6
        n_C = max(6, round(LLM_TARGET * 0.15))
        n_B = max(0, LLM_TARGET - n_C - n_D_fixed)

        # ── Tier B — clean semantic (unique party, exact amount, proof, NO reference) ──
        # The bulk of the LLM matcher's work — batched so it never sees them all at once.
        for k in range(n_B):
            cp = nextcp()
            num = f"WZB-B{k + 1:02d}"
            ccy = ("USD" if k % 4 == 0 else "EUR" if k % 6 == 0 else "SGD" if k % 9 == 0 else base)
            amt = round(2500 + k * 211.0, 2)
            idate = f"2026-06-{(k % 20) + 3:02d}"
            acct = a1 if k % 3 else a2
            emit(num, cp, ccy, amt, idate, tier="B", expected_status="auto", should_match=True,
                 **assign_source(),
                 credits=[credit(acct, idate, f"INWARD TT {cp.upper()} {ccy}", conv(ccy, amt))],
                 proof=(lambda inv, cp=cp, amt=amt, ccy=ccy, num=num, idate=idate:
                        _proof(sme_id, inv["invoice_id"], amt, ccy, idate, f"TRX-{num}",
                               sender=cp, bank="Standard Chartered")),
                 note="unique party + exact amount + proof → LLM should auto-match")

        # ── Tier C — weak-evidence matches: generic bank descriptions with no payer
        # name, only amount+date to go on. The matcher can propose on amount, but the
        # verifier CORRECTLY routes these to a human (auto-committing on amount alone is
        # risky) — so the right outcome is pending_review, not auto. Some the matcher
        # leaves unmatched entirely (too little to go on) — a realistic limitation. ──
        _C_DESCS = ["INWARD TT REF 0098871", "MISC INWARD CREDIT", "CROSS BORDER CREDIT",
                    "TT RECEIPT 55210", "IBG INWARD PAYMENT", "INWARD TT SGD",
                    "GIRO CREDIT ADVICE", "INWARD REMITTANCE", "SEPA CREDIT ADVICE",
                    "DUITNOW CREDIT"]
        _C_CCYS = ["USD", base, "EUR", "USD", base, "SGD"]
        for k in range(n_C):
            cp = nextcp()
            num = f"WZB-C{k + 1:02d}"
            ccy = _C_CCYS[k % len(_C_CCYS)]
            amt = round(2000 + k * 173.0, 2)
            var = -0.6 - (k % 5) * 0.2
            desc = _C_DESCS[k % len(_C_DESCS)]
            idate = f"2026-06-{(k % 18) + 4:02d}"
            acct = a1 if k % 2 else a2
            emit(num, cp, ccy, amt, idate, tier="C", expected_status="pending_review",
                 should_match=True, **assign_source(),
                 credits=[credit(acct, idate, desc, conv(ccy, amt, var))],
                 note="generic bank description (no payer name) → gate/verifier routes to human review")

        # ── Tier D — hard / error-prone (the accuracy limiters) ──
        # D1/D2: near-duplicate amounts + near-identical counterparty names (LLM may swap).
        emit("WZB-D01", "Meridian Components Sdn Bhd", base, 8800.0, "2026-06-12",
             tier="D", expected_status="auto", should_match=True, **assign_source(),
             credits=[credit(a1, "2026-06-12", "INWARD MERIDIAN COMPONENTS", 8800.0)],
             note="near-duplicate of D02 (amount 8800 vs 8850, similar name)")
        emit("WZB-D02", "Meridian Component (M) Sdn Bhd", base, 8850.0, "2026-06-13",
             tier="D", expected_status="auto", should_match=True, **assign_source(),
             credits=[credit(a1, "2026-06-13", "INWARD MERIDIAN COMPONENT M", 8850.0)],
             note="near-duplicate of D01")
        # D4/D5: two invoices, same amount, ONE credit — the credit belongs to D4 (its
        # description leans Alpha). The matcher must pick one and leave the other unmatched.
        emit("WZB-D04", "Alpha Trading Sdn Bhd", base, 5000.0, "2026-06-09",
             tier="D", expected_status="auto", should_match=True, **assign_source(),
             credits=[credit(a2, "2026-06-10", "INWARD ALPHA TRADING", 5000.0)],
             note="competes with D05 for a single 5000 credit; description leans Alpha")
        emit("WZB-D05", "Alpine Trading Sdn Bhd", base, 5000.0, "2026-06-09",
             tier="D", expected_status="unmatched", should_match=False, **assign_source(),
             credits=[], note="no credit of its own; must NOT steal D04's credit")
        # D6/D7: correct match but the credit is dated weeks before the invoice (stale date).
        emit("WZB-D06", "Pacific Rim Exports", "USD", 6400.0, "2026-06-15",
             tier="D", expected_status="auto", should_match=True, **assign_source(),
             credits=[credit(a1, "2026-06-15", "INWARD TT PACIFIC RIM EXPORTS USD",
                             conv("USD", 6400.0, -0.4), day="2026-04-18")],
             note="credit posted ~2 months before invoice date (stale) — matcher may reject on date")
        # D8/D9: abbreviated / renamed party vs the bank description (should still match).
        emit("WZB-D07", "Zenith Manufacturing Sdn Bhd", base, 7300.0, "2026-06-16",
             tier="D", expected_status="auto", should_match=True, **assign_source(),
             credits=[credit(a1, "2026-06-17", "INWARD ZENITH MFG", 7300.0)],
             proof=(lambda inv: _proof(sme_id, inv["invoice_id"], 7300.0, base, "2026-06-17",
                                       "TRX-ZEN-01", sender="Zenith Mfg", bank="Public Bank")),
             note="counterparty abbreviated 'Zenith Mfg' on the credit/proof")

        # ── Tier E — edge cases handled by the DETERMINISTIC gate/verifier/anomaly rules ──
        # Each carries a reference so the pre-pass matches it (no LLM needed); the tier's
        # point is the DISPOSITION (route-to-human / downgrade / flag), decided by rules.
        # E1: unmatched — invoice with no bank credit at all.
        emit("WZB-E01", "Tokyo Trading KK", "USD", 3200.0, "2026-06-20",
             tier="E", expected_status="unmatched", should_match=False, **assign_source(),
             credits=[], note="no payment received → stays unmatched")
        # E2: overpaid → gate ROUTE_TO_HUMAN (variance +4% is beyond the +2% auto band).
        emit("WZB-E02", "Penang Foods Industries", base, 6400.0, "2026-06-13",
             tier="E", expected_status="pending_review", should_match=True, **assign_source(),
             credits=[credit(a1, "2026-06-14", "IBG INWARD PENANG FOODS REF WZB-E02",
                             conv(base, 6400.0, 4.0), ref="WZB-E02")],
             tag="escalate_overpaid", note="overpaid +4% → gate routes to human")
        # E3: high value, NO proof → verifier downgrades the auto-commit to review.
        emit("WZB-E03", "Continental Mining Bhd", "USD", 14000.0, "2026-06-09",
             tier="E", expected_status="pending_review", should_match=True, **assign_source(),
             credits=[credit(a1, "2026-06-10", "INWARD TT CONTINENTAL MINING USD REF WZB-E03",
                             conv("USD", 14000.0, -0.3), ref="WZB-E03")],
             tag="b2_high_value_no_proof", note=">RM50k with no proof → verifier downgrade")
        # E4: reference decisiveness — no counterparty in the bank description, but the exact
        # reference is decisive so the pre-pass auto-commits. The weak-link verifier can't
        # touch it (it only sees still-unmatched txns, and this one is already consumed), so
        # it stays auto — the weak-link DOWNGRADE path is exercised by the Tier-C LLM matches.
        emit("WZB-E04", "Zephyr Holdings", base, 5300.0, "2026-06-14",
             tier="E", expected_status="auto", should_match=True, **assign_source(),
             credits=[credit(a1, "2026-06-15", "MISC INWARD CREDIT REF WZB-E04",
                             conv(base, 5300.0, -0.2), ref="WZB-E04")],
             tag="reference_decisive", note="exact reference auto-commits despite no name overlap")
        # E5: beneficiary mismatch — proof names a totally different paying party.
        emit("WZB-E05", "Dyeworks Ltd", "EUR", 4100.0, "2026-06-10",
             tier="E", expected_status="pending_review", should_match=True, **assign_source(),
             credits=[credit(a1, "2026-06-12", "SEPA INWARD DYEWORKS EUR REF WZB-E05",
                             conv("EUR", 4100.0, -0.5), ref="WZB-E05")],
             proof=(lambda inv: _proof(sme_id, inv["invoice_id"], 4100.0, "EUR", "2026-06-12",
                                       "SEPA-MISMATCH-1", sender="Unknown Shell Holdings",
                                       bank="Unknown Bank", account_number="ZZZ-999")),
             tag="beneficiary_mismatch", note="proof payer ≠ invoice counterparty → anomaly downgrade")
        # E6/E7: bank-detail change — same counterparty, two proofs, different account number.
        emit("WZB-E06", "Sentosa Exports", "USD", 5000.0, "2026-06-06",
             tier="E", expected_status="auto", should_match=True, **assign_source(),
             credits=[credit(a1, "2026-06-07", "INWARD TT SENTOSA EXPORTS USD REF WZB-E06",
                             conv("USD", 5000.0, -0.3), ref="WZB-E06")],
             proof=(lambda inv: _proof(sme_id, inv["invoice_id"], 5000.0, "USD", "2026-06-07",
                                       "SENTOSA-OLD", sender="Sentosa Exports", bank="OCBC",
                                       account_number="SEN-1111", uploaded="2026-06-07")),
             note="baseline beneficiary bank detail for Sentosa Exports")
        emit("WZB-E07", "Sentosa Exports", "USD", 5200.0, "2026-06-18",
             tier="E", expected_status="pending_review", should_match=True, **assign_source(),
             credits=[credit(a1, "2026-06-19", "INWARD TT SENTOSA EXPORTS USD REF WZB-E07",
                             conv("USD", 5200.0, -0.3), ref="WZB-E07")],
             proof=(lambda inv: _proof(sme_id, inv["invoice_id"], 5200.0, "USD", "2026-06-19",
                                       "SENTOSA-NEW", sender="Sentosa Exports", bank="HSBC",
                                       account_number="SEN-9999", uploaded="2026-06-19")),
             tag="bank_detail_change", note="same payee, changed bank/account vs E06 → anomaly downgrade")
        # E8: amount outlier — recurring counterparty at 6× its historical band. Has a proof
        # (so the high-value no-proof rule doesn't fire); the outlier is an ADVISORY anomaly
        # flag, so it stays auto — the point is the flag surfacing, not a downgrade.
        emit("WZB-E08", _RECURRING, base, _RECURRING_BAND * 6, "2026-06-16",
             tier="E", expected_status="auto", should_match=True, **assign_source(),
             credits=[credit(a1, "2026-06-17", f"INWARD {_RECURRING.upper()} LARGE REF WZB-E08",
                             conv(base, _RECURRING_BAND * 6, -0.2), ref="WZB-E08")],
             proof=(lambda inv: _proof(sme_id, inv["invoice_id"], _RECURRING_BAND * 6, base,
                                       "2026-06-17", "ACME-LARGE-1", sender=_RECURRING,
                                       bank="Maybank", recipient_reference="WZB-E08")),
             tag="amount_outlier", note="6× the historical band → anomaly flags (advisory, stays auto)")
        # E9/E10: duplicate invoice — same party+amount within 30 days, only ONE credit.
        emit("WZB-E09", "Selat Shipping Sdn Bhd", base, 5400.0, "2026-06-11",
             tier="E", expected_status="auto", should_match=True, **assign_source(),
             credits=[credit(a2, "2026-06-12", "DUITNOW SELAT SHIPPING REF WZB-E09", 5400.0, ref="WZB-E09")],
             tag="duplicate_invoice", note="one real payment; E10 is the double-billed twin")
        emit("WZB-E10", "Selat Shipping Sdn Bhd", base, 5400.0, "2026-06-12",
             tier="E", expected_status="unmatched", should_match=False, **assign_source(),
             credits=[], tag="duplicate_invoice", note="double-billed twin of E09 → no second credit → unmatched")

        # ── FAILURE paths (not scored) ──
        # Failed invoice parse (UI red "Failed" pill): error_message, no fields.
        invoices.append({
            "invoice_id": uid("inv", sme_id, "WZB-F01"), "sme_id": sme_id,
            "invoice_number": "WZB-F01", "counterparty_name": None, "invoice_currency": None,
            "invoice_amount": None, "invoice_date": None, "due_date": None, "status": "pending",
            "error_message": "PDF parse error: No readable text found in PDF (scanned image).",
            "source": "upload", "source_ref": None, "myinvois_uuid": None, "direction": None,
            "_tag": "failed_parse_invoice",
        })
        # Failed proof parse, anchored to the first invoice.
        proofs.append(_proof(sme_id, invoices[0]["invoice_id"], None, None, None,
                             "FAILED-PROOF-1", status="failed",
                             error="Image OCR/parse error: unreadable scan.",
                             tag="failed_parse_proof"))

        # ── Assemble statements per account (matching credits + deterministic noise). ──
        db_statements = []
        for ai, acct in enumerate(accounts):
            src = sme["accounts"][ai][5]
            is_feed = src == "bankfeed"
            rows = list(txns_by_acct[acct["account_id"]])
            # Fixed noise block: decoy credits/debits that make matching non-trivial.
            # Kept modest so the agent's post-pre-pass context (only unmatched rows) stays
            # small enough to reason over — the reference pre-pass clears the bulk first.
            n_noise = 8 if ai == 0 else 10
            rows += [_noise_txn(acct["account_id"], acct["currency_code"], rng,
                                f"2026-06-{rng.randint(1, 27):02d}") for _ in range(n_noise)]
            db_statements.append({
                "statement_id": uid("dbstmt", sme_id, acct["account_id"], ai),
                "account_id": acct["account_id"],
                "file_type": "feed" if is_feed else "csv",
                "file_path": (f"finverse://{uid('dbstmt', sme_id, acct['account_id'], ai)}"
                              if is_feed else f"seed://current-{ai}"),
                "source": "bankfeed" if is_feed else "upload",
                "period_start": "2026-06-01", "period_end": "2026-06-28",
                "parse_status": "completed", "transactions": rows,
            })

        # Seeded Finverse consent backing A2 (so the Settings linked-bank list is populated).
        bank_feed_link = {
            "link_id": uid("bflink", sme_id, a2["account_id"]),
            "sme_id": sme_id, "account_id": a2["account_id"],
            "finverse_login_id": f"seed-login-{a2['account_id'][:8]}",
            "institution": "CIMB Bank (Finverse)", "access_token": "seed-login-identity-token",
            "refresh_token": "seed-refresh-token", "status": "active",
        }

        # Mock connector credentials so Connect/Sync buttons are pre-configured for the demo.
        credentials = {
            "accounting": [
                {"sme_id": sme_id, "provider": "autocount", "environment": "mock", "company": sme["company_name"]},
                {"sme_id": sme_id, "provider": "sql", "environment": "mock", "company": sme["company_name"]},
            ],
            "myinvois": {"sme_id": sme_id, "model": "taxpayer", "environment": "mock",
                         "client_id": "mock-client-id", "client_secret": "mock-secret",
                         "tin": "C1234567890"},
        }

        # ── FILE set: the ~quarter of documents delivered as uploadable files. ──
        file_invoices, file_proofs = [], []
        file_stmt_rows = []
        f_ccys = [base, "USD", "EUR", "SGD", base, base, "USD", base, "EUR", base,
                  base, "USD", base, "EUR", base, base, "USD", base]
        for k in range(18):
            cp = nextcp()
            num = f"WZB-U{k + 1:02d}"
            ccy = f_ccys[k % len(f_ccys)]
            amt = round(2200 + k * 305.0, 2)
            idate = f"2026-06-{(k % 18) + 6:02d}"
            ifmt = "pdf" if k % 3 else "png"
            pfmt = "png" if k % 2 else "pdf"
            pref = f"UPL-{num}"
            converted = conv(ccy, amt)
            rail = "DuitNow" if ccy == base else None
            file_invoices.append({
                "invoice_number": num, "counterparty": cp, "currency": ccy, "amount": amt,
                "invoice_date": idate, "due_date": _due(idate), "format": ifmt,
                "expected_credit_base": converted})
            file_proofs.append({
                "reference": pref, "amount": amt, "currency": ccy, "date": idate,
                "corroborates_invoice": num, "format": pfmt, "sender": cp,
                "rail": rail, "recipient_reference": num})
            # The invoice number rides on both the receipt and the statement (recon key).
            file_stmt_rows.append({"date": idate, "description": f"INWARD {cp.upper()} {ccy}",
                                   "credit": converted, "reference": num})
            if ccy != base:
                add_fx(ccy, base, idate)

        file_statements = [
            {"filename": "statement_primary_iso.csv", "format": "csv_signed",
             "account_id": a1["account_id"], "currency": base,
             "role": "reconciliation driver for the file invoices (ISO date, signed amount)",
             "rows": file_stmt_rows},
            {"filename": "statement_ddmmyyyy.csv", "format": "csv_ddmmyyyy",
             "account_id": a1["account_id"], "currency": base,
             "role": "format coverage: dd/mm/yyyy dates + noise only",
             "rows": [{"date": "05/06/2026", "description": "OFFICE RENT TENANCY", "credit": -3200.0},
                      {"date": "09/06/2026", "description": "FPX ONLINE TRANSFER", "credit": 1820.0},
                      {"date": "14/06/2026", "description": "MONTHLY SERVICE CHARGE", "credit": -38.0}]},
            {"filename": "statement_debit_credit.xlsx", "format": "xlsx_debit_credit",
             "account_id": a2["account_id"], "currency": a2["currency_code"],
             "role": "format coverage: split debit/credit columns (xlsx)",
             "rows": [{"date": "2026-06-07", "description": "INWARD TT REFUND", "debit": 0.0, "credit": 1450.0},
                      {"date": "2026-06-12", "description": "CARD SETTLEMENT", "debit": 990.0, "credit": 0.0},
                      {"date": "2026-06-19", "description": "INTEREST CREDIT", "debit": 0.0, "credit": 22.5}]},
        ]

        datasets.append({
            "sme": {k: sme[k] for k in ("sme_id", "slug", "company_name", "registration_no",
                                        "email", "phone", "country_code", "base_ccy")},
            "accounts": accounts, "history": history,
            "bank_feed_link": bank_feed_link, "credentials": credentials,
            "db": {"statements": db_statements, "invoices": invoices, "proofs": proofs},
            "files": {"statements": file_statements, "invoices": file_invoices, "proofs": file_proofs},
            "expectations": expectations,
        })

    return {"datasets": datasets, "fx": list(fx_rows.values()), "password": DEMO_PASSWORD,
            "expectations": datasets[0]["expectations"], "time_model": TIME_MODEL}


if __name__ == "__main__":
    data = build()
    ds = data["datasets"][0]
    s = ds["sme"]
    n_txn = sum(len(st["transactions"]) for st in ds["db"]["statements"])
    tiers = {}
    for e in ds["expectations"]:
        tiers[e["tier"]] = tiers.get(e["tier"], 0) + 1
    # Sanity: deterministic ids stable; expected txns exist among seeded transactions.
    seeded_txn_ids = {t["transaction_id"] for st in ds["db"]["statements"] for t in st["transactions"]}
    for e in ds["expectations"]:
        if e["expected_transaction_id"]:
            assert e["expected_transaction_id"] in seeded_txn_ids, e["invoice_number"]
    assert build()["expectations"] == data["expectations"], "build() not deterministic"
    print(f"{s['company_name']}  {s['email']}")
    print(f"  accounts={len(ds['accounts'])}  histMatches={len(ds['history']['matches'])}")
    print(f"  dbInvoices={len(ds['db']['invoices'])}  dbTxns={n_txn}  dbProofs={len(ds['db']['proofs'])}")
    print(f"  fileInvoices={len(ds['files']['invoices'])}  fileProofs={len(ds['files']['proofs'])}")
    print(f"  expectations={len(ds['expectations'])}  tiers={dict(sorted(tiers.items()))}")
    print(f"  FX upserts={len(data['fx'])}")
